pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

dependencyResolutionManagement {
    Properties properties = new Properties()
    properties.load(file("local.properties").newInputStream())

    def localRepoPath = properties.getProperty('repositoryURL')

    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            name = 'LocalMaven'
            url = uri(localRepoPath)
        }
    }
}

rootProject.name = "PrivmxEndpoint"
include ':privmx-endpoint'
include ':privmx-endpoint-extra'
include ':privmx-endpoint-android'
include ':privmx-endpoint-jni'
include ':examples:privmx-snippets'

// streams
include ':privmx-endpoint-streams-android'
include ':privmx-endpoint-streams:jvm'

project(':privmx-endpoint-jni').projectDir = file("privmx-endpoint/src/main/cpp")