pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.5.0'
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "PrivmxEndpoint"
include ':privmx-endpoint'
include ':privmx-endpoint-extra'
include ':privmx-endpoint-android'

//Jni implementation of modules
include ':jni-wrappers'

//Streams modules
include ':privmx-endpoint-streams:jvm'
include ':privmx-endpoint-streams:android'


include ':examples:privmx-snippets'
include ':examples:privmx-snippets'
